cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart , name="add_cart"),
    path('',views.cart_details,name='cart_details'),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('delete/<int:product_id>/', views.cart_fullremove, name="cart_fullremove")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from payment import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('',include('products.urls')),
    path('user/' ,include('accounts.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from products.models import product
# Create your models here.

class Cart(models.Model):

    cart_id = models.CharField( max_length=250, blank=True)
    date_added = models.DateField( auto_now_add=True)
    razor_pay_order_id = models.CharField( max_length=100, null=True, blank=True)
    razor_pay_payment_id = models.CharField( max_length=100, null=True, blank=True)
    razor_pay_payment_signature = models.CharField( max_length=100, null=True, blank=True)


    class Meta:
        db_table= 'Cart'
        ordering= ['date_added']

    def __str__(self):
        return '{}'.format( self.cart_id)
    
class CartItem(models.Model):
    product = models.ForeignKey(product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)
    
    class Meta:
        db_table='CartItem'
        
    def sub_total(self):
        return self.product.product_price * self.quantity
    
    def __str__(self):
        return '{}'.format( self.product )
    
        
        

cart/views.py
from django.shortcuts import render,redirect, get_object_or_404
from products.models import product
from .models import Cart, CartItem
import razorpay
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart= request.session.create()
    return cart

def add_cart(request,product_id):
    products = product.objects.get(id=product_id)
    try :
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=products,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')

def cart_details(request,total=0,counter=0,items=None):
    try:
        cart= Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.product_price * cart_item.quantity)
            
            counter += cart_item.quantity
        
        
    except ObjectDoesNotExist:
        pass
    # client = razorpay.Client(auth = (settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))
    # payment = client.order.create({'amount':total, 'currency':'INR','payment_capture': 1 })
    # cart.razor_pay_order_id = payment['id']
    cart.save()
    
    
    # print("***********")
    # print(payment)
    # print("***********")

    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item = CartItem.objects.get(product=products,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect("cart:cart_details")

def cart_fullremove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item = CartItem.objects.get(product=products,cart=cart)
    cart_item.delete()
    return redirect("cart:cart_details")

templates/base.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />
    <style>
      .hr-lines{
        position: relative;
        max-width: 500px;
        margin: auto;
        text-align: center;
      }
      
      .hr-lines:before{
        content:" ";
        height: 2px;
        width: 130px;
        background: #BEC3DA;
        display: block;
        position: absolute;
        top: 50%;
        left: 0;
      }
      
      .hr-lines:after{
        content:" ";
        height: 2px;
        width: 130px;
        background: #BEC3DA;
        display: block;
        position: absolute;
        top: 50%;
        right: 0;
      }

    </style>
    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>
  <body>
    {% include 'navbar.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% block title %}
  {{ product.product_name }}
{% endblock %}
{% block content %}
<section class=" gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Cart - {{item_count}} items</h5>
            </div>
            <div class="card-body">
            {% if not cart_items  %}
            <h1>Your Cart is Empty</h1>
            {% else %}
              {% for cart_item in cart_items %}
              <!-- Single item -->
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <!-- Image -->
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <img src="{{ cart_item.product.product_image.url }}"
                      class="w-100" alt="Blue Jeans Jacket" />
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                  <!-- Image -->
                </div>
  
                <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                  <!-- Data -->
                  <p><strong>{{ cart_item.product.product_name }}</strong></p>
                  <p>Size: M</p>
                  <p>{{ cart_item.quantity }} x {{cart_item}}</p>
                  <a href="{% url 'cart:cart_fullremove' cart_item.product.id %}" type="button" class="btn btn-primary btn-sm me-1 mb-2" data-mdb-toggle="tooltip"
                    title="Remove item">
                    <i class="fas fa-trash"></i>
                </a>
                  <button type="button" class="btn btn-danger btn-sm mb-2" data-mdb-toggle="tooltip"
                    title="Move to the wish list">
                    <i class="fas fa-heart"></i>
                  </button>
                  <!-- Data -->
                </div>
  
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  <!-- Quantity -->
                  
                  <div class="d-flex mb-4" style="max-width: 300px">
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><button class="btn btn-primary px-3 me-2">
                      {% comment %} onclick="this.parentNode.querySelector('input[type=number]').stepDown()"> {% endcomment %}
                      <i class="fas fa-minus"></i>
                    </button></a>
                    
                    <div class="form-outline">
                      <input id="form1" min="0" name="quantity" value="{{ cart_item.quantity }}" type="number" class="form-control" disabled />
                      <label class="form-label" for="form1">Quantity</label>
                    </div>
                    {% if cart_item.quantity < cart_item.product.stock %}

                    <a href="{% url 'cart:add_cart' cart_item.product.id %}"><button class="btn btn-primary px-3 ms-2">
                      {% comment %} onclick="this.parentNode.querySelector('input[type=number]').stepUp()"> {% endcomment %}
                      <i class="fas fa-plus"></i>
                    </button></a>
                    {% endif %}
                  </div>

                  
                  <!-- Quantity -->
  
                  <!-- Price -->
                  <p class="text-start text-md-center">
                    <strong>${{cart_item.sub_total}}</strong>
                  </p>
                  <!-- Price -->
                </div>
              </div>
              <!-- Single item -->
              {% endfor %}
              {% endif %}
              <!-- Single item -->
            </div>
          </div>
          {% comment %} <div class="card mb-4">
            <div class="card-body">
              <p><strong>Expected shipping delivery</strong></p>
              <p class="mb-0">12.10.2020 - 14.10.2020</p>
            </div>
          </div> {% endcomment %}
          <div class="card mb-4 mb-lg-0">
            <div class="card-body">
              <p><strong>We accept</strong></p>
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard" />
             
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Summary</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                  Products
                  <span>${{total}}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Shipping
                  <span>$Free</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total amount</strong>
                    <strong>
                      <p class="mb-0">(including VAT)</p>
                    </strong>
                  </div>
                  
                  <span><strong>${{total}}</strong></span>
                </li>
              </ul>
  
              <button id="rzp-button1" class="btn btn-primary btn-lg btn-block">
                Go to checkout
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script scr="https://checkout.razorpay.com/v1/checkout.js"> </script>
  {% comment %} <script>
    var options = {
        "key": "rzp_test_2QDrBVLArOH78I", // Enter the Key ID generated from the Dashboard
        "amount": "{{payment.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
        "currency": "INR",
        "name": "ecom",
        "description": "Test Transaction",
        "image": "https://example.com/your_logo",
        "order_id": "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 2
        "handler": function (response){
            alert(response.razorpay_payment_id);
            alert(response.razorpay_order_id);
            alert(response.razorpay_signature)
        },
        "theme": {
            "color": "#3399cc"
        }
    };
    var rzp1 = new Razorpay(options);
    rzp1.on('payment.failed', function (response){
            alert(response.error.code);
            alert(response.error.description);
            alert(response.error.source);
            alert(response.error.step);
            alert(response.error.reason);
            alert(response.error.metadata.order_id);
            alert(response.error.metadata.payment_id);
    });
    document.getElementById('rzp-button1').onclick = function(e){
        rzp1.open();
        e.preventDefault();
    }
    </script> {% endcomment %}
  {% endblock %}

templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-white text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 link-secondary">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3 text-secondary"></i>Xiaomi Phones
            </h6>
            <p>
              ALWAYS BELIEVE
THAT SOMETHING WONDERFUL
IS ABOUT TO HAPPEN
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Mobile</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laptop</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Watch</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Television</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="{% url 'cart:cart_details' %}" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3 text-secondary"></i> India</p>
            <p>
              <i class="fas fa-envelope me-3 text-secondary"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3 text-secondary"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3 text-secondary"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.025);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/index.html
{% extends 'base.html' %}
{% block title %}
  Xioami India
{% endblock %}
{% block content %}
  <!-- Carousel wrapper -->
  <div id="carouselMaterialStyle" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <!-- Indicators -->
    <div class="carousel-indicators">
      <button type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide-to="2" aria-label="Slide 3"></button>
    </div>

    <!-- Inner -->
    <div class="carousel-inner rounded-5 shadow-4-strong">
      <!-- Single item -->
      <div class="carousel-item active">
        <a href=""><img src="https://i02.appmifile.com/346_operator_in/11/10/2022/4138b586572710296eeafe237b2cdedf.jpg" class="d-block w-100 h-60" alt="Sunset Over the City" /></a>
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>

      <!-- Single item -->
      <div class="carousel-item">
        <a href=""><img src="https://i02.appmifile.com/548_operator_in/12/10/2022/8d6470b99e90160dc9295a9d5c107b95.jpg" class="d-block w-100 h-60" alt="Canyon at Nigh" /></a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>

      <!-- Single item -->
      <div class="carousel-item">
        <a href="#"><img src="https://i02.appmifile.com/333_operator_in/11/10/2022/27bf9720ece24d42cd42a38fb9f89804.png" class="d-block w-100 h-60" alt="Cliff Above a Stormy Sea" /></a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <!-- Inner -->

    <!-- Controls -->
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselMaterialStyle" data-mdb-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <!-- Carousel wrapper -->
  <div class="container pt-5 pb-5">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <div class="col h-50">
        <div class="card h-100 bg-image hover-overlay ripple h-50">
          <img src="https://i02.appmifile.com/388_operator_in/11/10/2022/ccc7593b544ead967da84708dbe61adc.jpg?width=398&height=230" class="card-img-top img-fluid" alt="Skyscrapers" />
          <a href="#!"><div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div></a>
        </div>
      </div>
      <div class="col h-50">
        <div class="card h-100 bg-image hover-overlay ripple h-50">
          <img src="https://i02.appmifile.com/33_operator_in/10/10/2022/b4276deca03b861263087ac87b190996.jpg?width=398&height=230" class="card-img-top img-fluid" alt="Los Angeles Skyscrapers" />
          <a href="#!"><div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div></a>
        </div>
      </div>
      <div class="col h-50">
        <div class="card h-100 bg-image hover-overlay ripple h-50">
          <img src="https://i02.appmifile.com/459_operator_in/10/10/2022/9e52dae49291ae7da2c04325043e4e88.jpg?width=398&height=230" class="card-img-top img-fluid" alt="Palm Springs Road" />
          <a href="#!"><div class="mask" style="background-color: rgba(57, 192, 237, 0.2);"></div></a>
        </div>
      </div>
    </div>
  </div>

  <div></div>
  {% include 'productlist.html' %}
{% endblock %}

templates/product_details.html
{% extends 'base.html' %}
{% block title %}
  {{ product.product_name }}
{% endblock %}
{% block content %}
  <div>
    <div class="collapse sticky-top" id="navbarToggleExternalContent">
      <div class="bg-dark p-4">
        <h5 class="text-white h4 container">{{ product.product_name }}</h5>
        <h6 class="text-muted container">{{ product.product_discription }}</h6>
        <h6 class="text-muted container">$ {{ product.product_price }}</h6>
      </div>
    </div>
    <nav class="navbar navbar-dark bg-dark sticky-top">
      <div class="container container-fluid">
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fas fa-bars"></i></button>
      </div>
    </nav>
  </div>

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <!-- Grid row -->
      <div class="row wow fadeIn">
        <!-- Grid column -->
        <div class="col-md-6 mb-4">
          <img src="{{ product.product_image.url }}" class="img-fluid" alt="" />
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 mb-4">
          <!-- Content -->
          <div class="p-4">
            <div class="mb-3">
              <button type="button" class="btn btn-secondary" data-mdb-toggle="tooltip" data-mdb-html="true" title="{{ product.product_name }}">Mi Screen Protect</button>
              <button type="button" class="btn btn-secondary" data-mdb-toggle="tooltip" data-mdb-html="true" title="{{ product.product_name }}">10-days Replacement Policy</button>
              <button type="button" class="btn btn-secondary" data-mdb-toggle="tooltip" data-mdb-html="true" title="{{ product.product_name }}">Mi Exchange</button>
            </div>

            <p class="lead">
              <span class="text-danger"><strong>${{ product.product_price }}</strong></span>
              <span class="mr-1"><del>${{ product.product_price_original }}</del></span>
            </p>

            <p class="lead font-weight-bold">Description</p>
            <ul>
              <li>₹1,000 Discount on Checkout</li>
              <li>Flat ₹4,000 Instant Discount* with Axis Bank Debit and Credit Cards</li>
              <li>Up to ₹16,500 off with Mi Exchange</li>
              <li>Up to ₹3,000 cashback* with ZestMoney</li>
              <li>0% Interest | Up to 6 Months of NO Cost EMI</li>
            </ul>
            <form class="justify-content-center p-4">
              <!-- Default input -->
              <button class="btn btn-danger ">Buy now</button> 
              <a class="text-light btn btn-primary btn-md my-0 " style="text-decoration: none;" href="{% if user.is_authenticated %}{% url 'cart:add_cart' product.id %}{% else %}{% url 'login' %}{% endif %}">
                Add to cart<i class="fas fa-shopping-cart ml-1"></i></a>
              
            </form>
          </div>
          <!-- Content -->
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->

      <hr />

      <!-- Grid row -->
      <div class="row d-flex justify-content-center wow fadeIn">
        <!-- Grid column -->
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->

      <!-- Grid row -->
      <div class="row wow fadeIn">
        <!-- Grid column -->
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </main>
{% endblock %}